export PATH="$HOME/.local/bin:$PATH"

exec awesome

export XDG_CURRENT_DESKTOP=awesome
export GTK_USE_PORTAL=1

systemctl --user import-environment DISPLAY XAUTHORITY DBUS_SESSION_BUS_ADDRESS
dbus-update-activation-environment DISPLAY XAUTHORITY DBUS_SESSION_BUS_ADDRESS

exec dbus-run-session awesome
