export PATH="$HOME/.local/bin:$PATH"
export XDG_CURRENT_DESKTOP=awesome
export GTK_USE_PORTAL=1

xrandr --output DP-2 --mode 1920x1080 --rate 239.76 --primary

systemctl --user import-environment DISPLAY XAUTHORITY DBUS_SESSION_BUS_ADDRESS
dbus-update-activation-environment DISPLAY XAUTHORITY DBUS_SESSION_BUS_ADDRESS

exec dbus-run-session awesome
