#!/usr/bin/env bash

SCRIPTS_DIR="$HOME/.config/rofi/scripts"
KNOWN_ENTRIES="powermenu clipboard emoji snippets wifi bluetooth projects ssh media strawberry easyeffects wallpaper calc bookmarks docker tmux search tabs speedtest translate logs port"

if [ -n "$1" ]; then
    case " $KNOWN_ENTRIES " in
        *" $1 "*) ;;
        *) exit 1 ;;
    esac
    case "$1" in
        powermenu) script="system_prompt" ;;
        *)         script="$1" ;;
    esac
    (export ROFI_PARENT_ITEM="$1"; exec "$SCRIPTS_DIR/$script") >/dev/null 2>&1 &
    exit 0
fi

printf "powermenu\nclipboard\nemoji\nsnippets\nwifi\nbluetooth\nprojects\nssh\nmedia\nstrawberry\neasyeffects\nwallpaper\ncalc\nbookmarks\ndocker\ntmux\nsearch\ntabs\nspeedtest\ntranslate\nlogs\nport\n"
